# Generated by Django 6.0.2 on 2026-02-23 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_hospital_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='photo_url',
            field=models.URLField(blank=True),
        ),
    ]
